// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOu_R505G06rlRejTPzRzJlK-W4OPKYmE',
    appId: '1:160251355917:web:cb8633ece17a613ec10644',
    messagingSenderId: '160251355917',
    projectId: 'firechat-1958e',
    authDomain: 'firechat-1958e.firebaseapp.com',
    storageBucket: 'firechat-1958e.appspot.com',
    measurementId: 'G-MV6NDB8ET1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd6zoG4TQTdovSj3CRWpFCHkxCyTlBTBY',
    appId: '1:160251355917:android:09117bd544b36860c10644',
    messagingSenderId: '160251355917',
    projectId: 'firechat-1958e',
    storageBucket: 'firechat-1958e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaNxu-vJIc0LBP0Krbq1RiEUByy3gmi9c',
    appId: '1:160251355917:ios:8f2fd6f7af617b67c10644',
    messagingSenderId: '160251355917',
    projectId: 'firechat-1958e',
    storageBucket: 'firechat-1958e.appspot.com',
    iosBundleId: 'ipg.elegant.fireChat',
  );
}
